version: "3"
services:
  app_react:
    build: ./
    container_name: app_react
    volumes:
      - build_react:/var/www/html
    networks:
      - my-network

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_react
    external_links:
      - node_app
    networks:
      - my-network

volumes:
  build_react:

networks:
  my-network:
    external: true
